name: Build and Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and Comment
        uses: ayushdabhi31/Build_Url@23.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
