name: Post Build Zip

on:
  pull_request:
     types: [opened, synchronize, reopened]
     branches:
        - main

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        run: npm install
      
      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Build project & zip
        run: npm run build && zip -r build.zip build

      - name: React app build.zip PR comment
        uses: ayushdabhi31/Build_Url@22.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
