on:
  pull_request:
     types: [opened, synchronize, reopened]
     branches:
        - main
  
jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Post PR Comment
        uses: ayushdabhi31/Build_Url@1.1-alpha
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
